# Generated by Django 3.0.4 on 2020-03-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airconapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='ac_brand_name',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_name',
            new_name='ac_model_name',
        ),
    ]
