# Generated by Django 3.0.4 on 2020-03-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airconapp', '0003_auto_20200316_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airconapp.Brand'),
        ),
    ]
